version: "3.8"

x-common-variables: &common-variables
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: example

services:
  client:
    image: payment-client
    container_name: payment-client
    restart: always
    build: ./client
    volumes:
      - ./client/:/usr/src/app
  api:
    image: payment-api
    container_name: payment-api
    restart: always
    build: ./api
    volumes:
      - ./api/:/usr/src/app
    depends_on:
      - db
    environment:
      <<: *common-variables
  db:
    image: mongo
    container_name: payment-db
    restart: always
    volumes:
      - data-volume:/data/db
      - data-config:/data/configdb
    environment:
      <<: *common-variables
  nginx:
    image: payment-nginx
    container_name: payment-nginx
    depends_on:
      - api
      - client
    restart: always
    build: ./nginx
    ports:
      - "3000:80"

volumes:
  data-volume:
  data-config:
